spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.181.189.110:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /sell